### ISSUE TITLE
Is it possible to hide the runtime window?

### ISSUE THREAD

**Issue by kidzgy** [erik434/TrayIconBuster#1]
![微信截图_20240109112339](https://github.com/erik434/TrayIconBuster/assets/6967810/c3ea1fda-ec19-4f48-a523-5e0b8536b6e3)
The moment it runs, a batch window pops up and then disappears instantly. Is it possible to hide this window?

**Comment by erik434** [comment]
You might be able to change the build config so it builds as a graphical program instead of a console app (which is why it spawns a console when you run it directly).

An easier solution would probably be to download [NirCmd](https://www.nirsoft.net/utils/nircmd.html) and use it to launch the program with a hidden window. For example: `nircmd.exe exec hide path\to\TrayIconBuster.exe`

**Comment by kidzgy** [comment]
> You might be able to change the build config so it builds as a graphical program instead of a console app (which is why it spawns a console when you run it directly).
> 
> An easier solution would probably be to download [NirCmd](https://www.nirsoft.net/utils/nircmd.html) and use it to launch the program with a hidden window. For example: `nircmd.exe exec hide path\to\TrayIconBuster.exe`

Is it possible to provide a released version of the graphical program? Thank you very much!

**Comment by erik434** [comment]
Sure! Turns out it was just a 1-line change. For me at least this seems to prevent any console popups when launching the program. If that doesn't work for you, I'd suggest NirCmd as a good alternative.

**Comment by kidzgy** [comment]
I'm sorry, I didn't have time to test it for a while the other day. I just tested it and found that the OutputType in TrayIconBuster.csproj was changed to WinExe, and after regenerating the program, no more batch windows were displayed. Thanks!

**Comment by erik434** [comment]
Great! Glad that did the trick :)
